### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by daitcl** [crifan/honkit_template#3]
CURRENT_USER=desktop-42h9jl6\35476
系统找不到指定的路径。
Using Python command: python3
---Current Config---
ENABLE_COMMIT_GITHUB_IO=false
ENABLE_UPDATE_GITHUB_IO_README=false
ENABLE_DEPLOY_SERVER=false
ENABLE_RSYNC_PROXY=false
RSYNC_PROXY=
RSYNC_PARAMS=-avzh --progress --stats --delete --force
process_begin: CreateProcess(NULL, tput -Txterm setaf 2, ...) failed.
process_begin: CreateProcess(NULL, tput -Txterm setaf 3, ...) failed.
process_begin: CreateProcess(NULL, tput -Txterm setaf 7, ...) failed.
process_begin: CreateProcess(NULL, tput -Txterm sgr0, ...) failed.
--------------------------------------------------------------------------------
Author  : crifan.org
Version : 20240927
Function: Auto use Honkit to generated files: website/pdf/epub/mobi; upload to remote server; commit to your github.io repository
                Run 'make help' to see usage
                Latest version: https://github.com/crifan/honkit_template
--------------------------------------------------------------------------------
CURRENT_DIR=D:/Users/35476/Desktop/honkit/honkit_template/books/honkit_demo
BOOK_NAME=honkit_demo
../../common/honkit_makefile.mk:384: recipe for target 'sync_readme_to_book' failed
make: *** [sync_readme_to_book] Error 9009

**Comment by crifan** [comment]
原因：不支持Python3
解决办法：下载最新代码。因为最新代码中已合并了之前别人的PR：[2](https://github.com/crifan/honkit_template/pull/2)，已添加支持Python3了
